### ISSUE TITLE
Wrong version listed on pypi?

### ISSUE THREAD

**Issue by trevor** [sunng87/pyclj#12]
Version 0.3.0 is listed on pypi:

https://pypi.python.org/pypi/pyclj/0.3.0
Uploaded on: 2013-02-07

However version 0.2.2 appears to be the latest:

https://pypi.python.org/pypi/pyclj/0.2.2
Uploaded on: 2014-06-10

**Comment by sunng87** [comment]
Sorry for confusing, the version 0.3.0 is uploaded by mistake. Please use the HEAD version (0.2.2). 

I have configured pypi to hide 0.3.0. Seems I need to remote this release totally.
