### ISSUE TITLE
Version 0.3.0 disappeared from PyPi

### ISSUE THREAD

**Issue by ChristopherRabotin** [sunng87/pyclj#13]
From at least July 2014 until yesterday (17 June 2015), I had `pyclj==0.3.0` in my requirements file for a project. However, version 0.3.0 seems to have completely disappeared from PyPi: where did it go?

I'm falling back on pyclj==0.2.2 since the latest release here on Github is that version, but I'm crossing my finger that this won't break the Python datomic package.

**Comment by sunng87** [comment]
Sorry, I just removed 0.3.0 from pypi yesterday because someone complains that version code is confusing. Please use 0.2.2 as it's even newer than 0.3.0.

Sorry for the inconvenience.
